### PR TITLE
Update README to not use v3 prefix

### PR DESCRIPTION
**Pull request by M-Yamashita01**
We tried to download jwt v3 by reference to README, however, We could not download the jwt v3, because it cannot find the package.

```
❯ go get github.com/cristalhq/jwt/v3
cannot find package "github.com/cristalhq/jwt/v3" in any of:
	/usr/local/go/src/github.com/cristalhq/jwt/v3 (from $GOROOT)
	/Users/xxxxx/go/src/github.com/cristalhq/jwt/v3 (from $GOPATH)
```

Therefore, we thought it necessary to update the README and changed the code to not use v3.

### CODE REVIEW

**Comment by cristaloleg** [comment]
Hi there, thank you for the PR. Here is the Go modules trick:

1. if you're in module (folder or tree with a `go.mod`) running `go get github.com/cristalhq/jwt/v3` will install the latest v3 module version (which is good and should be made).
2. however if you're not in the module, Go will try to fetch `github.com/cristalhq/jwt/v3` as a package.

I'm not 100% sure which command should be mentioned in README. From one point everyone should start using modules and this command simplifies installation. From the other side not everyone is aware of `go get` outside the module. 

I would like to postpone with merge as see more feedback from the users. Ok?

**Comment by M-Yamashita01** [comment]
> 1. if you're in module (folder or tree with a go.mod) running go get github.com/cristalhq/jwt/v3 will install the latest v3 module version (which is good and should be made).
> 2. however if you're not in the module, Go will try to fetch github.com/cristalhq/jwt/v3 as a package.

I didn't know that. Thank you for your explanation.
I will try it.

> I would like to postpone with merge as see more feedback from the users. Ok?

Yes, please.

**Comment by cristaloleg** [comment]
Hi, see https://github.com/cristalhq/jwt/pull/93

**Comment by cristaloleg** [comment]
Closing as resolved in another PR. Thank you @M-Yamashita01 for pointing! <3

**Pull request closed without merging**
