### PR TITLE
add sync.Pool to get hash.Hash where possible

### PR DESCRIPTION
**Pull request by FZambia**
Similar to #44, just to make the same for all algorithms.

```
benchcmp bench.old bench.new
benchmark                        old ns/op     new ns/op     delta
BenchmarkEDSA/Sign-EdDSA-4       66128         66932         +1.22%
BenchmarkEDSA/Verify-EdDSA-4     170415        171653        +0.73%
BenchmarkES/Sign-ES256-4         35060         36800         +4.96%
BenchmarkES/Verify-ES256-4       95878         102948        +7.37%
BenchmarkES/Sign-ES384-4         5640494       5328269       -5.54%
BenchmarkES/Verify-ES384-4       14693353      11951887      -18.66%
BenchmarkES/Sign-ES512-4         11918140      9458677       -20.64%
BenchmarkES/Verify-ES512-4       27179389      20391382      -24.97%
BenchmarkPS/Sign-PS256-4         2079814       1979967       -4.80%
BenchmarkPS/Verify-PS256-4       110701        88832         -19.76%
BenchmarkPS/Sign-PS384-4         2741718       1868684       -31.84%
BenchmarkPS/Verify-PS384-4       161826        86363         -46.63%
BenchmarkPS/Sign-PS512-4         2559179       1869384       -26.95%
BenchmarkPS/Verify-PS512-4       95496         83714         -12.34%
BenchmarkRS/Sign-RS256-4         1864396       1860276       -0.22%
BenchmarkRS/Verify-RS256-4       84125         80451         -4.37%
BenchmarkRS/Sign-RS384-4         1884087       1909896       +1.37%
BenchmarkRS/Verify-RS384-4       80976         86621         +6.97%
BenchmarkRS/Sign-RS512-4         1867908       1894707       +1.43%
BenchmarkRS/Verify-RS512-4       80037         79639         -0.50%
BenchmarkHS/Sign-HS256-4         3322          2914          -12.28%
BenchmarkHS/Verify-HS256-4       1667          1299          -22.08%
BenchmarkHS/Sign-HS384-4         3724          2998          -19.50%
BenchmarkHS/Verify-HS384-4       1991          1410          -29.18%
BenchmarkHS/Sign-HS512-4         3884          3086          -20.55%
BenchmarkHS/Verify-HS512-4       2429          1435          -40.92%

benchmark                        old allocs     new allocs     delta
BenchmarkEDSA/Sign-EdDSA-4       18             18             +0.00%
BenchmarkEDSA/Verify-EdDSA-4     2              2              +0.00%
BenchmarkES/Sign-ES256-4         51             50             -1.96%
BenchmarkES/Verify-ES256-4       21             20             -4.76%
BenchmarkES/Sign-ES384-4         14474          14457          -0.12%
BenchmarkES/Verify-ES384-4       29655          32629          +10.03%
BenchmarkES/Sign-ES512-4         19591          19617          +0.13%
BenchmarkES/Verify-ES512-4       50897          37498          -26.33%
BenchmarkPS/Sign-PS256-4         129            128            -0.78%
BenchmarkPS/Verify-PS256-4       19             18             -5.26%
BenchmarkPS/Sign-PS384-4         129            128            -0.78%
BenchmarkPS/Verify-PS384-4       19             18             -5.26%
BenchmarkPS/Sign-PS512-4         129            128            -0.78%
BenchmarkPS/Verify-PS512-4       19             18             -5.26%
BenchmarkRS/Sign-RS256-4         123            122            -0.81%
BenchmarkRS/Verify-RS256-4       13             12             -7.69%
BenchmarkRS/Sign-RS384-4         123            122            -0.81%
BenchmarkRS/Verify-RS384-4       13             12             -7.69%
BenchmarkRS/Sign-RS512-4         123            122            -0.81%
BenchmarkRS/Verify-RS512-4       13             12             -7.69%
BenchmarkHS/Sign-HS256-4         18             13             -27.78%
BenchmarkHS/Verify-HS256-4       6              1              -83.33%
BenchmarkHS/Sign-HS384-4         18             13             -27.78%
BenchmarkHS/Verify-HS384-4       6              1              -83.33%
BenchmarkHS/Sign-HS512-4         18             13             -27.78%
BenchmarkHS/Verify-HS512-4       6              1              -83.33%

benchmark                        old bytes     new bytes     delta
BenchmarkEDSA/Sign-EdDSA-4       1424          1424          +0.00%
BenchmarkEDSA/Verify-EdDSA-4     293           295           +0.68%
BenchmarkES/Sign-ES256-4         3954          3826          -3.24%
BenchmarkES/Verify-ES256-4       1255          1131          -9.88%
BenchmarkES/Sign-ES384-4         1752088       1750090       -0.11%
BenchmarkES/Verify-ES384-4       3589214       3949067       +10.03%
BenchmarkES/Sign-ES512-4         3027917       3032247       +0.14%
BenchmarkES/Verify-ES512-4       7866515       5795388       -26.33%
BenchmarkPS/Sign-PS256-4         32892         32771         -0.37%
BenchmarkPS/Verify-PS256-4       5912          5762          -2.54%
BenchmarkPS/Sign-PS384-4         33097         32890         -0.63%
BenchmarkPS/Verify-PS384-4       6152          5909          -3.95%
BenchmarkPS/Sign-PS512-4         33125         32901         -0.68%
BenchmarkPS/Verify-PS512-4       6191          5949          -3.91%
BenchmarkRS/Sign-RS256-4         32247         32121         -0.39%
BenchmarkRS/Verify-RS256-4       5426          5297          -2.38%
BenchmarkRS/Sign-RS384-4         32355         32132         -0.69%
BenchmarkRS/Verify-RS384-4       5532          5311          -3.99%
BenchmarkRS/Sign-RS512-4         32370         32158         -0.65%
BenchmarkRS/Verify-RS512-4       5545          5329          -3.90%
BenchmarkHS/Sign-HS256-4         1328          848           -36.14%
BenchmarkHS/Verify-HS256-4       512           32            -93.75%
BenchmarkHS/Sign-HS384-4         1696          896           -47.17%
BenchmarkHS/Verify-HS384-4       848           48            -94.34%
BenchmarkHS/Sign-HS512-4         1776          976           -45.05%
BenchmarkHS/Verify-HS512-4       864           64            -92.59%
```

### CODE REVIEW

**Comment by storozhukBM** [comment]
@FZambia Looks good.
I'd suggest you run all benchmarks with `-count=10` then `benchstat` will show us the variance of the measurements. Then I'd use it only for algorithms that show some measurable difference. Maybe it worth removing the pool for EdDSA and maybe RS family, but it will be more evident after remeasurements.

**Comment by FZambia** [comment]
Yeah - it's definetely worth removing for EdDSA and RSA since most time and mem spent inside other calls.

**Comment by FZambia** [comment]
Interesting, I was expecting at least notable improvement in algorithms other then HMAC, but actually it only makes sense for HMAC. Here is benchstat after 10 tests:
```
name                 old time/op    new time/op    delta
EDSA/Sign-EdDSA-4      65.8µs ± 1%    65.8µs ± 1%     ~     (p=0.780 n=9+10)
EDSA/Verify-EdDSA-4     167µs ± 3%     168µs ± 3%     ~     (p=0.529 n=10+10)
ES/Sign-ES256-4        35.1µs ± 2%    35.1µs ± 1%     ~     (p=0.829 n=10+8)
ES/Verify-ES256-4      97.8µs ± 4%   105.4µs ± 5%   +7.80%  (p=0.000 n=10+10)
ES/Sign-ES384-4        5.22ms ± 1%    5.50ms ± 6%   +5.28%  (p=0.000 n=9+10)
ES/Verify-ES384-4      11.4ms ± 4%    11.4ms ± 3%     ~     (p=0.971 n=10+10)
ES/Sign-ES512-4        9.34ms ± 3%    9.83ms ±16%     ~     (p=0.393 n=10+10)
ES/Verify-ES512-4      22.0ms ± 6%    20.9ms ±18%     ~     (p=0.549 n=9+10)
PS/Sign-PS256-4        1.83ms ± 1%    1.87ms ± 1%   +2.22%  (p=0.000 n=10+10)
PS/Verify-PS256-4      83.5µs ± 3%    83.7µs ± 1%     ~     (p=0.315 n=10+9)
PS/Sign-PS384-4        1.83ms ± 1%    1.87ms ± 3%   +2.36%  (p=0.000 n=10+10)
PS/Verify-PS384-4      81.4µs ± 1%    83.2µs ± 1%   +2.26%  (p=0.000 n=9+10)
PS/Sign-PS512-4        1.84ms ± 2%    1.87ms ± 2%   +1.19%  (p=0.008 n=10+9)
PS/Verify-PS512-4      82.5µs ± 2%    80.4µs ± 1%   -2.54%  (p=0.000 n=9+9)
RS/Sign-RS256-4        1.86ms ± 1%    1.83ms ± 1%   -1.50%  (p=0.001 n=8+9)
RS/Verify-RS256-4      80.1µs ± 1%    80.4µs ± 0%   +0.47%  (p=0.015 n=9+8)
RS/Sign-RS384-4        1.87ms ± 3%    1.85ms ± 1%     ~     (p=0.315 n=10+9)
RS/Verify-RS384-4      79.6µs ± 2%    77.6µs ± 0%   -2.46%  (p=0.000 n=9+9)
RS/Sign-RS512-4        1.85ms ± 1%    1.84ms ± 1%   -0.68%  (p=0.017 n=10+9)
RS/Verify-RS512-4      80.4µs ± 2%    77.7µs ± 1%   -3.33%  (p=0.000 n=10+9)
HS/Sign-HS256-4        3.24µs ± 3%    2.85µs ± 1%  -11.89%  (p=0.000 n=9+9)
HS/Verify-HS256-4      1.62µs ± 1%    1.29µs ± 1%  -19.90%  (p=0.000 n=9+10)
HS/Sign-HS384-4        3.54µs ± 1%    3.00µs ± 1%  -15.15%  (p=0.000 n=9+9)
HS/Verify-HS384-4      1.90µs ± 1%    1.40µs ± 3%  -26.09%  (p=0.000 n=10+9)
HS/Sign-HS512-4        3.58µs ± 1%    3.05µs ± 1%  -14.89%  (p=0.000 n=10+10)
HS/Verify-HS512-4      1.91µs ± 1%    1.42µs ± 1%  -25.73%  (p=0.000 n=9+9)

name                 old alloc/op   new alloc/op   delta
EDSA/Sign-EdDSA-4      1.42kB ± 0%    1.42kB ± 0%     ~     (all equal)
EDSA/Verify-EdDSA-4      294B ± 0%      294B ± 0%     ~     (p=0.081 n=10+10)
ES/Sign-ES256-4        3.95kB ± 0%    3.83kB ± 0%   -3.23%  (p=0.000 n=10+10)
ES/Verify-ES256-4      1.26kB ± 0%    1.13kB ± 0%  -10.12%  (p=0.000 n=10+10)
ES/Sign-ES384-4        1.75MB ± 0%    1.75MB ± 0%     ~     (p=0.393 n=10+10)
ES/Verify-ES384-4      3.86MB ± 4%    3.86MB ± 3%     ~     (p=0.912 n=10+10)
ES/Sign-ES512-4        3.03MB ± 0%    3.03MB ± 0%     ~     (p=0.796 n=10+10)
ES/Verify-ES512-4      7.33MB ± 6%    6.86MB ±18%     ~     (p=0.447 n=9+10)
PS/Sign-PS256-4        32.9kB ± 0%    32.8kB ± 0%   -0.37%  (p=0.000 n=10+10)
PS/Verify-PS256-4      5.89kB ± 0%    5.76kB ± 0%   -2.15%  (p=0.000 n=10+10)
PS/Sign-PS384-4        33.1kB ± 0%    32.9kB ± 0%   -0.66%  (p=0.000 n=10+10)
PS/Verify-PS384-4      6.13kB ± 0%    5.91kB ± 0%   -3.61%  (p=0.000 n=10+10)
PS/Sign-PS512-4        33.1kB ± 0%    32.9kB ± 0%   -0.65%  (p=0.000 n=10+10)
PS/Verify-PS512-4      6.18kB ± 0%    5.95kB ± 0%   -3.63%  (p=0.000 n=10+9)
RS/Sign-RS256-4        32.2kB ± 0%    32.1kB ± 0%   -0.39%  (p=0.000 n=10+10)
RS/Verify-RS256-4      5.42kB ± 0%    5.30kB ± 0%   -2.36%  (p=0.000 n=10+10)
RS/Sign-RS384-4        32.4kB ± 0%    32.1kB ± 0%   -0.67%  (p=0.000 n=10+10)
RS/Verify-RS384-4      5.54kB ± 0%    5.31kB ± 0%   -4.06%  (p=0.000 n=10+10)
RS/Sign-RS512-4        32.4kB ± 0%    32.2kB ± 0%   -0.68%  (p=0.000 n=10+10)
RS/Verify-RS512-4      5.55kB ± 0%    5.33kB ± 0%   -4.04%  (p=0.000 n=10+10)
HS/Sign-HS256-4        1.33kB ± 0%    0.85kB ± 0%  -36.14%  (p=0.000 n=10+10)
HS/Verify-HS256-4        512B ± 0%       32B ± 0%  -93.75%  (p=0.000 n=10+10)
HS/Sign-HS384-4        1.70kB ± 0%    0.90kB ± 0%  -47.17%  (p=0.000 n=10+10)
HS/Verify-HS384-4        848B ± 0%       48B ± 0%  -94.34%  (p=0.000 n=10+10)
HS/Sign-HS512-4        1.78kB ± 0%    0.98kB ± 0%  -45.05%  (p=0.000 n=10+10)
HS/Verify-HS512-4        864B ± 0%       64B ± 0%  -92.59%  (p=0.000 n=10+10)

name                 old allocs/op  new allocs/op  delta
EDSA/Sign-EdDSA-4        18.0 ± 0%      18.0 ± 0%     ~     (all equal)
EDSA/Verify-EdDSA-4      2.00 ± 0%      2.00 ± 0%     ~     (all equal)
ES/Sign-ES256-4          51.0 ± 0%      50.0 ± 0%   -1.96%  (p=0.000 n=10+10)
ES/Verify-ES256-4        21.0 ± 0%      20.0 ± 0%   -4.76%  (p=0.000 n=10+10)
ES/Sign-ES384-4         14.4k ± 0%     14.4k ± 0%     ~     (p=0.448 n=10+10)
ES/Verify-ES384-4       31.9k ± 4%     31.9k ± 3%     ~     (p=0.896 n=10+10)
ES/Sign-ES512-4         19.6k ± 0%     19.6k ± 0%     ~     (p=0.699 n=10+10)
ES/Verify-ES512-4       47.4k ± 6%     44.4k ±18%     ~     (p=0.447 n=9+10)
PS/Sign-PS256-4           129 ± 0%       128 ± 0%   -0.78%  (p=0.000 n=10+10)
PS/Verify-PS256-4        19.0 ± 0%      18.0 ± 0%   -5.26%  (p=0.000 n=10+10)
PS/Sign-PS384-4           129 ± 0%       128 ± 0%   -0.78%  (p=0.000 n=10+10)
PS/Verify-PS384-4        19.0 ± 0%      18.0 ± 0%   -5.26%  (p=0.000 n=10+10)
PS/Sign-PS512-4           129 ± 0%       128 ± 0%   -0.78%  (p=0.000 n=10+10)
PS/Verify-PS512-4        19.0 ± 0%      18.0 ± 0%   -5.26%  (p=0.000 n=10+10)
RS/Sign-RS256-4           123 ± 0%       122 ± 0%   -0.81%  (p=0.000 n=10+10)
RS/Verify-RS256-4        13.0 ± 0%      12.0 ± 0%   -7.69%  (p=0.000 n=10+10)
RS/Sign-RS384-4           123 ± 0%       122 ± 0%   -0.81%  (p=0.000 n=10+10)
RS/Verify-RS384-4        13.0 ± 0%      12.0 ± 0%   -7.69%  (p=0.000 n=10+10)
RS/Sign-RS512-4           123 ± 0%       122 ± 0%   -0.81%  (p=0.000 n=10+10)
RS/Verify-RS512-4        13.0 ± 0%      12.0 ± 0%   -7.69%  (p=0.000 n=10+10)
HS/Sign-HS256-4          18.0 ± 0%      13.0 ± 0%  -27.78%  (p=0.000 n=10+10)
HS/Verify-HS256-4        6.00 ± 0%      1.00 ± 0%  -83.33%  (p=0.000 n=10+10)
HS/Sign-HS384-4          18.0 ± 0%      13.0 ± 0%  -27.78%  (p=0.000 n=10+10)
HS/Verify-HS384-4        6.00 ± 0%      1.00 ± 0%  -83.33%  (p=0.000 n=10+10)
HS/Sign-HS512-4          18.0 ± 0%      13.0 ± 0%  -27.78%  (p=0.000 n=10+10)
HS/Verify-HS512-4        6.00 ± 0%      1.00 ± 0%  -83.33%  (p=0.000 n=10+10)
```

**Comment by FZambia** [comment]
Closing - first measurements in PR were a mistake due to test env inconsistency and I was tricked. Thanks @storozhukBM for pointing at statistics error.

**Pull request closed without merging**
